### ISSUE TITLE
Why does the mod block the entire error message?

### ISSUE THREAD

**Issue by TechPro424** [henkelmax/hide-ip#1]
In the example in the readme, I noticed that the mod hides the entire error message
Why can't it just hide the ip?

**Comment by henkelmax** [comment]
It was a quick and dirty fix.
Its a little more complicated to actually just hide the IP, since it also sometimes shows the reverse DNS entry.
So for security reasons, I just hid everything just to be on the safe side.
I might change it later, but since it is a Minecraft bug, it might actually get fixed in 1.18 anyways (https://bugs.mojang.com/browse/MC-237608).
